controller_manager:
  ros__parameters:
    update_rate: 30

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    swerve_drive_controller:
      type: swerve_drive_controller/SwerveDriveController
    

joint_broad:
  ros__parameters:
    update_rate: 30

swerve_drive_controller:
  ros__parameters:
    wheel_joint_names:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_right_wheel_joint
      - rear_left_wheel_joint
    steer_joint_names:
      - front_left_wheel_rotate_joint
      - front_right_wheel_rotate_joint
      - rear_right_wheel_rotate_joint
      - rear_left_wheel_rotate_joint
    wheelbase: 0.635
    trackwidth: 0.635